config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations}
  get 'landing/welcome'
  get 'landing/signin'


  resources :users, only: [:index, :show] do
    get :autocomplete_user_username, :on => :collection
    member do
      get :follow
      get :unfollow
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      member do
        get :like
        get :unlike
      end
    end
    resources :newsfeeds, only: [:index]
  end


  root 'landing#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, polymorphic: true
  belongs_to :follower,   polymorphic: true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ApplicationRecord
    include PublicActivity::Model
    tracked owner: Proc.new { |controller, model| controller && controller.current_user }
    belongs_to :user
    has_many :comments
    has_many_attached :images
    acts_as_votable
    validates :title, presence: true, length: { maximum: 50}
    validates :description, presence: true, length: { maximum: 800}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :username, presence: true, length: { maximum: 30 }
  validates :bio, length: { maximum: 500 }  

  has_many :posts
  has_many :comments
  acts_as_follower
  acts_as_followable
  acts_as_voter



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include PublicActivity::StoreController


    before_action :config_params, if: :devise_controller? 


    def config_params
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
        devise_parameter_sanitizer.permit(:account_update, keys: [:bio, :website])

    end


    def after_sign_in_path_for(resource)
        user_path(resource.id)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @user = current_user
        @post = Post.find(params[:post_id])
        @comment = @user.comments.new
    end 

    def create
        @user = current_user
        @post = Post.find(params[:post_id])
        @comment = @user.comments.build(comment_params)
        if @comment.save
            redirect_to @post.user
        else
            render :new
        end
    end


    def destroy
        
        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to @comment.post.user
    end





    private

    def comment_params
        params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :signed_in? 
  def welcome
  end

  def signin
  end





  private

  def signed_in?
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/newsfeeds_controller.rb
class NewsfeedsController < ApplicationController

  before_action :check_user

  def index
    @activities = PublicActivity::Activity.where(:owner_id => current_user.following_users, :owner_type => 'User').order('created_at DESC')
  end




  private


  def check_user
    @user = User.find(params[:user_id])
    if current_user.id == @user.id

    else
      redirect_to @user
    end
  end



 

 





  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @user = User.find(params[:user_id])
    @comments = @post.comments
  end

  def like
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.liked_by(current_user)
    redirect_to user_newsfeeds_url(current_user)
  end

  def unlike
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.unliked_by(current_user)
    redirect_to user_newsfeeds_url(current_user)
  end

  # GET /posts/new
  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @user, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, images: [])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


    
    def after_update_path_for(resource)
        user_path(resource.id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  autocomplete :user, :username


  def index
    if params[:search]
      @user = User.where('username LIKE ?', "%#{params[:search]}").order('username')
        if @user.exists?
          redirect_to user_path(@user.ids)
        else
          flash[:alert] = "The User #{params[:search]} was not found"
          @user = User.find(params[:id])
          redirect_to @user
        end

    end
  end
  def show
    @user = User.find(params[:id])
    @posts = @user.posts


   
  end






  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to @user
  end


  
  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



    def resource_name
        :user
    end

    def resource_class
        User
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h3>hello</h3>

app/views/landing/signin.html.erb
<div class="container">
    <div class="d-flex justify-content-center flex-row">

        <div class="col-lg-5 col-md-8 col-sm-8">
            <div class="card p-3 text-center">
                <div class="card-body">
                    <h1 class="insta-font">RailsGram</h1>
                    <hr>

                    <%= render 'devise/sessions/signin'%>
                </div>
            </div>
               <div class="card mt-2 text-center">
                    <div class="card-body">
                   
                        <p>Already have an account? <%= link_to "Sign Up", landing_welcome_path %></p>

                     </div>
                </div>
        </div>
    </div>

</div>

app/views/landing/welcome.html.erb
<div class="container" style="height: 100vh;">

        <div class="d-flex h-100 justify-content-center flex-wrap align-items-start flex-row">

            <div class="col-lg-6 col-md-4 p-2 mt-5">
                <%= image_tag ("iphone.png"), class: 'img-responsive', style: "width: 100%;"%>
            </div>

            <div class="col-lg-5 col-md-8 p-3 mt-3">

                <div class="card p-3 text-center">

                    <div class="card-body">
                
                
                            <h1 class="insta-font">RailsGram</h1>
                            <h5 class="text-muted">
                                Sign up to see photos and videos from your friends.
                            </h5>
                        <hr>
                        <br>
                            <%= render 'devise/registrations/signup'%>
                        <br>
                            <p class="text-muted">
                            By signing up, you agree to our Terms . Learn how we collect, use and share your data in our Data Policy and how we use cookies and similar technology in our Cookies Policy.
                            </p>
                    </div>

                </div>

                <div class="card mt-2 text-center">
                    <div class="card-body">
                   
                        <p>Already have an account? <%= link_to "Sign In", landing_signin_path %></p>

                     </div>
                </div>

            </div>

        </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">

  </head>

  <body class="bg-light">
  <% if user_signed_in? %>
  <%= render 'shared/nav'%>

  <% end %>

  

  <div class="text-center">
  <br><br>
  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
  </div>
   

    <%= yield %>
  </body>
</html>

app/views/newsfeeds/index.html.erb
<div class="container">
<div id="modal_content">
    
    </div>

    <div class="d-flex justify-content-center flex-row">

        <div class="col-lg-5 col-md-8 col-sm-8">

        <% @activities.each do |act|%>
        <div class="card mb-3">

                <div class="card-header bg-white">
                <%= act.owner.username %>
                </div>

                <%= image_tag(act.trackable.images.first, class: 'img-responsive', style: "width: 100%; height: 100%;")%>

                <div class="card-body">

                    <% if current_user.voted_for?(act.trackable)%>
                             <%= link_to unlike_user_post_path(act.owner.id, act.trackable.id) do%>
                                <%= octicon "heart", :fill => "red",:height => 32,  :class => "right left", :"aria-label" => "hi" %> <%= act.trackable.get_likes.size %>
            
                                <% end %>

                    <% else %>
                        <%= link_to like_user_post_path(act.owner.id, act.trackable.id) do%>
                            <%= octicon "heart", :height => 32,  :class => "right left", :"aria-label" => "hi" %> <%= act.trackable.get_likes.size %>
            
                         <% end %>

                    <% end %>
               
                </div>
                   
            </div>
        <% end %>
            

        
        </div>
    </div>

</div>

app/views/posts/_form.html.erb
<div class="container">
    <div class="d-flex justify-content-center flex-row">

        <div class="col-lg-5 col-md-8 col-sm-8">
            <div class="card p-3 text-center">

            <div class="card-header bg-white">
              Upload an Image
            </div>
                <div class="card-body">

<%= form_for ([@user, @post]) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control'  %>
  </div>

  <div class="actions">
    <%= form.submit "Upload Image", class: 'btn btn-outline-success btn-block'%>
  </div>
<% end %>
<br><br>

<%= link_to 'Back', user_path(@user) %>


                </div>
              </div>
            </div>
            </div>

      </div>

app/views/posts/_post.html.erb
<div class="modal col-md-12 bd-example-modal-lg fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class=" modal-dialog modal-dialog-centered modal-lg"  role="document">
        <div class="modal-content anyClass p-2" id="modal_content" style="height: 80vh;">

            <div class="modal-body">
            <div class="row">
            
           
                <div class="col-lg-8">
                    <div class="card">
                    <% if post.images.count > 1 %>

                    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <% post.images.each.with_index(0) do |image, index| %>
                                <div class="carousel-item <%= index.zero? ? 'active' : '' %> ">
                                    <%= image_tag image, class: 'd-block w-100'%>
                          
                                </div>
                              <% end %>

                        </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
</div>
                    <% else %>
                        <%= image_tag(post.images.first, class: 'img-responsive', style: "width: 100%; height: 100%")%>
                          <% end %>

                    </div>
                
                </div>



                <div class="col-lg-4">
                    <div class="d-inline-flex align-items-baseline">
                        <p class="mr-3"><%= post.user.username %></p>
                        

                        

                        <% if current_user.following?(post.user) %>
                           <%= link_to "Unfollow", unfollow_user_path, class: 'btn btn-primary btn-sm'%>

                        <% else %>
                            <%= link_to "Follow", follow_user_path, class: 'btn btn-primary btn-sm'%>


                        <% end %>   
                        <% if current_user.id == post.user.id %>
                        <%= link_to "Delete", user_post_path(post.user, post), class: 'btn btn-outline-danger btn-sm', method: :delete, data: { confirm: "Are you sure?"}%> 
                        <% end %>    
                        </div>

                        <p><b><%= post.description%></b></p>

                    <hr>



                    <div class="col-md-12 no-padding anyClass">
                        <% @comments.each do |comment| %>
                            <p><b><%= comment.user.username %></b> 
                            <% if current_user.id == comment.user.id || current_user.id == post.user.id %>
                            <%= link_to "x", user_post_comment_path(post.user, post, comment), method: :delete, class: 'btn btn-outline-danger btn-sm', style: "font-size: 8px;"%>: 
                            <% end %>
                            <%= comment.content %></p>


                        <% end %>
                   
                        <p><b>JohnGambo</b>: super awesome!!!</p>


                    </div>

                     <%= form_for ([post.user, post, Comment.new]) do |f| %>
                        <%= f.hidden_field :post_id, :value => post.id %>

                        <div class="form-group">
                         <%= f.text_field :content, class: 'form-control' %>

                        </div>
                        <%= f.submit "Add comment", class: 'btn btn-outline-primary btn-sm' %>

                    <% end %>

                    <hr>
                    <% if current_user.voted_for?(post)%>
                             <%= link_to unlike_user_post_path(post.user.id, post.id) do%>
                                <%= octicon "heart", :fill => "red",:height => 32,  :class => "right left", :"aria-label" => "hi" %> <%= post.get_likes.size %>
            
                                <% end %>

                    <% else %>
                        <%= link_to like_user_post_path(post.user.id, post.id) do%>
                            <%= octicon "heart", :height => 32,  :class => "right left", :"aria-label" => "hi" %> <%= post.get_likes.size %>
            
                         <% end %>

                    <% end %>
                </div>


                 </div>
            
            </div>


            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            
            </div>

        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<%= render 'form'  %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<% @post.images.each do |image|%>

  <%= image_tag (image), class: 'img-card-top', style: "width: 200px; height: 100%;"%>

<% end %>

<%= link_to 'Edit', edit_user_post_path(@post) %> |
<%= link_to 'Back', user_path(@post.user) %>

app/views/posts/show.js.erb
$('#modal_content').html("<%= j render 'post', post: @post %>")
$('#myModal').modal('show');

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light p-3 bg-white border-bottom">
  <a class="navbar-brand insta-font" href="#">RailsGram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= form_tag(users_path, :method => "get", id: "search-form", class: 'form-inline ml-auto my-1 my-lg-0') do %>
      <%= text_field_tag :search, params[:search], class: "search-query form-control mr-sm-2", placeholder: "Find user", type: "search", data: {autocomplete: autocomplete_user_username_users_path} %>  
        <%= submit_tag "Search", class: 'btn btn-outline-primary my-2 my-sm-0' %>
    <% end %>
  
    <ul class="navbar-nav ml-md-auto">
      
     
      <li class="nav-item">
        <%= link_to user_path(current_user.id), class: 'nav-link' do %>
      <%= octicon "home", :height => 25 %>

        <% end %>
      </li>
      <li class="nav-item">
       <%= link_to user_newsfeeds_path(current_user.id), class: 'nav-link' do%>
        <%= octicon "comment-discussion", :height => 25 %>

       <% end %>

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= octicon "person", :height => 25 %>

        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Upload Image", new_user_post_path(current_user), class: 'dropdown-item'%>

          <div class="dropdown-divider"></div>
           <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'dropdown-item'%>

        </div>
      </li>
      
    </ul>
    
  </div>
</nav>

app/views/users/show.html.erb
<div class="container">

  

    <div id="modal_content">
    
    </div>



    <div class="d-flex flex-md-row flex-md-wrap justify-content-center">

        <div class="col-md-3 d-flex justify-content-center">
        
            <%= image_tag("new_york.jpg", class: 'rounded-circle', style: "width: 130px; height: 130px;") %>
        </div>


        <div class="col-lg-4 col-md-4 d-flex flex-row flex-wrap justify-content-start align-items-start">

            <div class="d-inline-flex flex-wrap align-items-baseline">
                <h5 class="mr-3"><%= @user.email %></h5>
                    <% if user_signed_in? %>
                        <% if current_user.id == @user.id %>
                            <%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-outline-secondary btn-sm'%>
                        <% else %>

                            <% if current_user.following?(@user) %>
                            <%= link_to "Unfollow", unfollow_user_path, class: 'btn btn-primary btn-sm'%>

                            <% else %>
                                <%= link_to "Follow", follow_user_path, class: 'btn btn-primary btn-sm'%>


                            <% end %>
                        <% end %>

                    <% else %>
                    <%= link_to root_path do%>
                    <button class="btn btn-primary btn-sm">Follow</button>
                    <% end %>

                    <% end %>

                    
            </div>




            <div class="d-inline-flex flex-wrap pt-3 align-items-center">
            
                <p class="mr-3">Posts: <%= @user.posts.count %></p>
                <p class="mr-3">Follows: <%= @user.follow_count %></p>
                <p class="mr-3">Followers: <%= @user.followers_count %></p>

            </div>
            
            
            
            <p><%= @user.bio %></p>
            <br>
            <% if !@user.website.nil? %>
            <p><%= link_to @user.website %></p>
               
            <% end %>
           
            

            

        
        </div>

        
        
    
    </div>
     <hr>



    <div class="row">

        <% @posts.each do |post| %>
            <div class="col-md-4 mb-3">
                <div class="card h-100"> 
                <%= link_to user_post_path(post.user, post), remote: true  do %>
                    <%= image_tag(post.images.first, class: 'img-responsive', style: "width: 100%; height: 100%;")%>

                <% end %>
                </div>
                
            </div>

        <% end %>
        
         
    
    </div>

</div>